### PR TITLE
Fix bug: It doesn't adapt events read from journal.

### PR DESCRIPTION
**Pull request by ygree**
Noticed that this inmemory implementation doesn't adapt events read from journal. This PR fixes it.

### CODE REVIEW

**Comment by dnvriend** [comment]
Hi, thanks for the PR. Its a really nice feature to have. I will give it some thought and discussion with the akka team before merging, as akka query spec doesn't mention event adapters.

**Comment by ygree** [comment]
We've faced this when run tests, because we use your plugin for tests whereas during normal run we use different

**Comment by dnvriend** [comment]
Please dont close its a good discussion, I am asking Konrad what his ideas about it are and why the other plug-ins do this feature with disregard to the spec

**Comment by dnvriend** [comment]
Update to this PR. There is an ongoing discussion to making EventAdapters first class citizen to akka-persistence-query. The tickets are [Akka Ticket #18050 - Integrate EventAdapters to the Query side](https://github.com/akka/akka/issues/18050), [Akka Persistence Cassandra Ticket #116 - Optionally apply event adapters in queries](https://github.com/akka/akka/issues/18050) and [Akka Ticket #21065 - Make using EventAdapters nicer in PersistenceQuery](https://github.com/akka/akka/issues/21065). For now a workaround (like your PR) and implemented in LevelDB and akka-persistence-cassandra for example would solve any immediate usage problems. I will look into both the Cassandra and LevelDB implementations and your PR and see if it is compatible with the EventAdapter configuration used in both.

**Comment by ygree** [comment]
@dnvriend Sounds good! Thanks for update!

**Comment by dnvriend** [comment]
Hi, based on your PR I have adapted the code and strategy just a little bit and adopted the akka-persistence-cassandra and levelDB strategy. The strategy is that the readPlugin must contain a write-plugin section so that it knows which writePluginId writes events to the journal. Based on that knowledge, the readPlugin will get the event adapters from that writePlugin and use those event adapters to adapt events from the data model to the application model. Version 1.3.9 of the inmemory plugin will be released shortly. Thanks again!

**Comment by ygree** [comment]
@dnvriend Thanks a lot for the release!

**Pull request closed without merging**
